services:
  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_DB: ${DATABASE__POSTGRES_DB}
      POSTGRES_USER: ${DATABASE__POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE__POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
    restart: "unless-stopped"
    volumes:
      - tg-assistant-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE__POSTGRES_USER} -d ${DATABASE__POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.2-alpine3.21
    restart: "unless-stopped"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  reminder:
    build:
      context: .
      dockerfile: scheduler.dockerfile
    command: sh ./schedule_entrypoint.sh
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    restart: "unless-stopped"

  tg_assistant:
    build:
      context: .
      dockerfile: bot.dockerfile
    command: sh ./entrypoint.sh
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "unless-stopped"

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    command: sh ./api_entrypoint.sh
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: "unless-stopped"

volumes:
  tg-assistant-data:
  redis-data:
