"""empty message

Revision ID: 38942e06dd47
Revises:
Create Date: 2026-03-21 10:08:27.230219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38942e06dd47"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "DAILY", "WEEKLY", "MONTHLY", "SIXMONTH", "YEARLY", name="event_repeat_intervals"
    ).create(op.get_bind())
    op.create_table(
        "user",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("lastname", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_user_telegram_id")),
    )
    op.create_table(
        "event",
        sa.Column("event_datetime", sa.DateTime(True), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "repeat_interval",
            postgresql.ENUM(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "SIXMONTH",
                "YEARLY",
                name="event_repeat_intervals",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_event_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    op.drop_table("user")
    sa.Enum(
        "DAILY", "WEEKLY", "MONTHLY", "SIXMONTH", "YEARLY", name="event_repeat_intervals"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
